name: Build and Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # expondo secrets como variáveis de ambiente para os steps (runtime)
    env:
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Create public/env.js (runtime config)
        run: |
          mkdir -p public
          cat > public/env.js <<EOF
          window.__ENV = {
            PUBLIC_SUPABASE_URL: "${PUBLIC_SUPABASE_URL}",
            PUBLIC_SUPABASE_ANON_KEY: "${PUBLIC_SUPABASE_ANON_KEY}"
          };
          EOF

      - name: Build (Astro)
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
